### ISSUE TITLE
OCSD_ERR_TEST_SS_TO_DECODER error occured when I get trace from my custom CSAL

### ISSUE THREAD

**Issue by roppinhoppin** [Linaro/OpenCSD#20]
I created [my custom CSAL library](https://github.com/roppinhoppin/CSAL) to add support for Jetson TX2 board and it works almost correctly(Fetching cstrace.bin succeeds).
However when executing trc_pkt_lister in Jetson TX2 snapshot directory, trc_pkt_lister says as follows.
```
Trace Packet Lister: CS Decode library testing
-----------------------------------------------

** Library Version : 0.12.0

Test Command Line:-
trc_pkt_lister   --decode  

Trace Packet Lister : Warning: Ignored unknown option --decode.
Trace Packet Lister : reading snapshot from path ./
Using ETB_0 as trace source
ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapshot to decode tree conversion error]; Unrecognized Core 
name unknown. Cannot evaluate profile or architecture.ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapsho
t to decode tree conversion error]; Failed to create decoder for source ETM_3.
ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapshot to decode tree conversion error]; Unrecognized Core name unknown. Cannot evaluate profile or architecture.ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapshot to decode tree conversion error]; Failed to create decoder for source ETM_4.
ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapshot to decode tree conversion error]; Unrecognized Core name unknown. Cannot evaluate profile or architecture.ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapshot to decode tree conversion error]; Failed to create decoder for source ETM_5.
ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapshot to decode tree conversion error]; Unrecognized Core name unknown. Cannot evaluate profile or architecture.ss2_dcdtree : 0x0026 (OCSD_ERR_TEST_SS_TO_DECODER) [test snapshot to decode tree conversion error]; Failed to create decoder for source ETM_6.
```

Is this error caused by the lack of implementation of my CSAL registration function? or the lack of support in OpenCSD library?

**Comment by mikel-armbb** [comment]
Hi,

The current library has a mapping between core name e.g. Cortex-A53 and the architecture implemented. If you have a core name that is not recognised then this will result in the above error.

Either use a supported core name that matches the architecture of the core you are using, or add the name to the mapping function in the library.

A future version of the library may add generic architecture mapping to the library.

Mike

**Comment by roppinhoppin** [comment]
Thank you for replying me!
I just fixed the core name as Cortex-A57 in my .ini file and it finally works!
I really appreciate your advice, thank you!
