### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by OBorce** [Linaro/OpenCSD#21]
https://github.com/Linaro/OpenCSD/blob/466722fa5f97f6558cff559d111557c2394332a2/decoder/source/ocsd_dcd_tree.cpp#L534

https://github.com/Linaro/OpenCSD/blob/466722fa5f97f6558cff559d111557c2394332a2/decoder/source/trc_component.cpp#L88

are never destroyed?

**Comment by mikel-armbb** [comment]
Thanks for this report. This issue will be addressed in the next release.

Regards

Mike

**Comment by OBorce** [comment]
Thanks,
fixed in Version 0.12.2
