### ISSUE TITLE
OpenCSD not work on the etr dump

### ISSUE THREAD

**Issue by JoeyJiao** [Linaro/OpenCSD#22]
Hi Mike,
I cannot attach the dump into github, so send a email to you instead.

OpenCSD cannot decode the etm binary attached, however an opensource ETM decoder https://github.com/hwangcc23/ptm2human can parse.

Can you help understand why?

And is there any bug in OpenCSD?

Thanks

Joey

**Comment by mikel-armbb** [comment]
Issue continued by direct mail.
