### ISSUE TITLE
A missing comma found by Clang's latest -Wstring-concatenation

### ISSUE THREAD

**Issue by yabinc** [Linaro/OpenCSD#31]
In https://github.com/Linaro/OpenCSD/blob/master/decoder/source/etmv3/trc_pkt_elem_etmv3.cpp#L662,
  "Reserved","PE Reset","Reserved","HardFault"

A comma is missing after "HardFault"?

**Comment by yabinc** [comment]
external/OpenCSD/decoder/source/etmv3/trc_pkt_elem_etmv3.cpp:663:9: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
        \"Reserved\",\"BusFault\",\"Reserved\",\"Reserved\"

**Comment by mikel-armbb** [comment]
Hi,

Thanks for this report.
Will fix in next release.

Mike

**Comment by mikel-armbb** [comment]
fixed in v0.14.4
