### ISSUE TITLE
Build without static is broken

### ISSUE THREAD

**Issue by ggardet** [Linaro/OpenCSD#33]
Since https://github.com/Linaro/OpenCSD/commit/e7240a4f817c8354dd379087574874c6e34b54aa we can use `DISABLE_STATIC=1` to not build static binaries. 
But https://github.com/Linaro/OpenCSD/commit/f14d8040e07c8ba671e3379069de1e59956f8dba added some static binaries not guarded. This should be properly guarded with some `ifndef DISABLE_STATIC`.

**Comment by mikel-armbb** [comment]
Hi,

I note that the DISABLE_STATIC guards against _installation_ of static libraries, not necessarily the building of those libraries (depending on the sequence of building used).

Following a report from a user who was having difficulties building his application against the static libraries, the additional build instructions in f14d804 add in a build of the test program against the static libraries as part of the validation process.

It should be noted that while static libraries may well now be built despite using DISABLE_STATIC=1, the primary functionality is retained - no static libraries are installed, the new static linked test program is not installed.

Thanks

Mike

**Comment by mikel-armbb** [comment]
Further to the above. If I checkout 0.14.3 (prior to f14d804 ) and execute a clean build as follows:-

make install DISABLE_STATIC=1

Then the static libaries are in fact built but not installed, just as after f14d804.

Can you tell me the build command line that you used with DISABLE_STATIC=1 that did not build the static libraries.

Thanks

Mike

**Comment by ggardet** [comment]
With `0.14.4` , my build failed on `-static` build as the build environment is not setup for that. However, `0.14.2` built fine. 
I skipped version `0.14.3`.

**Comment by mikel-armbb** [comment]
Fixed in 1.0.0
