### ISSUE TITLE
decoder/docs/html not published

### ISSUE THREAD

**Issue by ggardet** [Linaro/OpenCSD#34]
`decoder/docs/html/*` is not generated and not part of the git repo. It would be great to add html docs to avoid every distro to regenerate it.

**Comment by mikel-armbb** [comment]
Hi,

The html docs can be generated in < 10 s on my machine.

Generating this and adding to github to publish would add 40MB of html files and binary artefacts to the repo - and cause hugh churn as each .html file has an embedded "generated on <date>" embedded.
Some artefact files have auto-generated file names.

Therefore it is not desirable or practical to publish the generated .html in the repo. 

Those distros that do want the include the .html docs can do so with very little effort in generating the documentation at the same time as they build the library.

Thanks

Mike
