### ISSUE TITLE
`perf` require massive mmap area when using `tmc_etr0`

### ISSUE THREAD

**Issue by jwnhy** [Linaro/OpenCSD#41]
System:
    Board: DragonBoard 410c
    System: Linux linaro-developer 5.15.7-01849-g9bc25b368335 #2 SMP PREEMPT Sun Feb 27 22:40:22 CST 2022 aarch64 GNU/Linux
    Kernel Option: All coresight related option is on.
    perf version: 5.16.11 (installed from `apt`)

Related Kernel Options:
(are there any other should I enable?)
```
CONFIG_CORESIGHT=y
CONFIG_CORESIGHT_LINKS_AND_SINKS=y
CONFIG_CORESIGHT_LINK_AND_SINK_TMC=y
CONFIG_CORESIGHT_CATU=y
CONFIG_CORESIGHT_SINK_TPIU=y
CONFIG_CORESIGHT_SINK_ETBV10=y
CONFIG_CORESIGHT_SOURCE_ETM4X=y
CONFIG_CORESIGHT_STM=y
CONFIG_CORESIGHT_CPU_DEBUG=y
CONFIG_CORESIGHT_CTI=y
CONFIG_CORESIGHT_CTI_INTEGRATION_REGS=y
CONFIG_CORESIGHT_TRBE=y
```

The command:
```bash
perf record -vvv -e cs_etm/@tmc_etr0/ --per-thread uname
```

The output:
```
Using CPUID 0x00000000410fd030
Attempting to add event pmu 'cs_etm' with 'tmc_etr0,' that may result in non-fatt
al errors
After aliases, add event pmu 'cs_etm' with 'tmc_etr0,' that may result in non-faa
tal errors
nr_cblocks: 0
affinity: SYS
mmap flush: 1
comp level: 0
------------------------------------------------------------
perf_event_attr:
  type                             7
  size                             128
  { sample_period, sample_freq }   1
  sample_type                      IP|TID|IDENTIFIER
  read_format                      ID
  disabled                         1
  exclude_kernel                   1
  exclude_hv                       1
  enable_on_exec                   1
  sample_id_all                    1
  exclude_guest                    1
  { bp_len, config2 }              0xa6509eae
------------------------------------------------------------
sys_perf_event_open: pid 2474  cpu -1  group_fd -1  flags 0x8 = 5
------------------------------------------------------------
perf_event_attr:
  type                             1
  size                             128
  config                           0x9
  { sample_period, sample_freq }   1
  sample_type                      IP|TID|IDENTIFIER
  read_format                      ID
  disabled                         1
  exclude_kernel                   1
  exclude_hv                       1
  mmap                             1
  comm                             1
  enable_on_exec                   1
  task                             1
  sample_id_all                    1
  exclude_guest                    1
  mmap2                            1
  comm_exec                        1
  context_switch                   1
  ksymbol                          1
------------------------------------------------------------
sys_perf_event_open: pid 2474  cpu -1  group_fd -1  flags 0x8 = 6
mmap size 528384B
AUX area mmap length 4194304
failed to mmap AUX area
failed to mmap with 12 (Cannot allocate memory)
```
I guess it is something wrong with the `perf`?
I read the doc which says upstream `perf` is fine.
If not where should I look for a workable `perf`?

Thanks in advance for your kind help and time.

**Comment by mikel-armbb** [comment]
Hi,

This is indeed a perf issue and not an OpenCSD issue.
The default AUX mmap size for perf should be 32 pages - though that may have changed.
perf command line options can be used to control the memory buffer sizes - see the perf record manual.

I recommend that in future for general coresight issues post to the coresight@lists.linaro.org mailing list where a lot of coresight / perf discussion and patches are posted.

Closing issue as not OpenCSD related

Thanks

Mike
===============================================

My version of perf (built some time ago outputs the following with the same command line:-

sys_perf_event_open: pid 3980  cpu -1  group_fd -1  flags 0x8 = 6
mmap size 266240B
AUX area mmap length 131072
Synthesizing TSC conversion information
Synthesizing auxtrace information
Control descriptor is not initialized
Linux
auxtrace idx 0 old 0 head 0x9710 diff 0x9710
[ perf record: Woken up 1 times to write data ]
overlapping maps in [vdso] (disable tui for more info)
failed to write feature CPUDESC
failed to write feature CACHE
failed to write feature MEM_TOPOLOGY
failed to write feature CPU_PMU_CAPS
