### ISSUE TITLE
Using OpenCSD with Android target?

### ISSUE THREAD

**Issue by mosfetfb** [Linaro/OpenCSD#46]
I'm attempting to use OpenCSD to decode the cs-etm data (perf.data) recorded on an Android target via simpleperf. I believe the formats should be the same but the binary locations on Android (I'm using AOSP 12) are different (there is no ~/.debug folder). I'm wondering if anyone's tried this or has instructions they can give?

**Comment by mikel-armbb** [comment]
Using perf / simple perf with OpenCSD is beyond the scope of the OpenCSD issues page - these should be specific issues discovered with the library.

Please address questions to an appropriate mailing list - either on for simpleperf, or coresight@lists.linaro.org may be able to help

Thanks

Mike
