### ISSUE TITLE
ETMv4 Exception Target Hand-Over

### ISSUE THREAD

**Issue by albertschulz** [Linaro/OpenCSD#56]
I would like to discuss the exception target address handling for ETMv4 decoding.

In my use-case, I am interested in the target address of an exception.
The information exists in the raw trace, and also in the raw trace packets.
Unfortunately, it is filtered in the trace element output.

See the following trace:
```javascript
Idx:676; ID:10; [0x95 0xaa 0x42 ];	I_ADDR_S_IS0 : Address, Short, IS0.; Addr=0xFFFFFFFF801084A8 ~[0x84A8]
Idx:681; ID:10; [0x06 0x1d ];	I_EXCEPT : Exception.;  IRQ; Ret Addr Follows;
Idx:683; ID:10; [0x95 0x2c ];	I_ADDR_S_IS0 : Address, Short, IS0.; Addr=0xFFFFFFFF801084B0 ~[0xB0]
Idx:681; ID:10; OCSD_GEN_TRC_ELEM_INSTR_RANGE(exec range=0xffffffff801084a8:[0xffffffff801084b0] num_i(2) last_sz(4) (ISA=A64) E --- )
Idx:681; ID:10; OCSD_GEN_TRC_ELEM_EXCEPTION(pref ret addr:0xffffffff801084b0; excep num (0x0e) )
Idx:688; ID:10; [0x85 0x20 0x0a 0x1c 0x80 0x00 0x00 0x00 0x00 0x32 ];	I_ADDR_CTXT_L_64IS0 : Address & Context, Long, 64 bit, IS0.; Addr=0x00000000801C1480; Ctxt: AArch64,EL2, NS; 
Idx:701; ID:10; [0x04 ];	I_TRACE_ON : Trace On.
Idx:704; ID:10; [0x85 0x20 0x58 0x22 0x80 0xff 0xff 0xff 0xff 0xf1 0x01 0xa0 0x7a 0x97 0x80 ];	I_ADDR_CTXT_L_64IS0 : Address & Context, Long, 64 bit, IS0.; Addr=0xFFFFFFFF8022B080; Ctxt: AArch64,EL1, NS; CID=0x80977aa0; VMID=0x0001; 
Idx:722; ID:10; [0xf7 ];	I_ATOM_F1 : Atom format 1.; E
Idx:688; ID:10; OCSD_GEN_TRC_ELEM_PE_CONTEXT((ISA=A64) EL2N; 64-bit; VMID=0x1; CTXTID=0x80977aa0; )
Idx:701; ID:10; OCSD_GEN_TRC_ELEM_TRACE_ON( [begin or filter])
Idx:704; ID:10; OCSD_GEN_TRC_ELEM_PE_CONTEXT((ISA=A64) EL1N; 64-bit; VMID=0x1; CTXTID=0x80977aa0; )
Idx:722; ID:10; OCSD_GEN_TRC_ELEM_INSTR_RANGE(exec range=0xffffffff8022b080:[0xffffffff8022b084] num_i(1) last_sz(4) (ISA=A64) E BR  )
```

Im my example, the exception target space is filtered (target-side, in coresight).

At `Idx:688`, the target address is available as CONTEXT + ADDR packet.
But results in no trace element, but only the CONTEXT information (OCSD_GEN_TRC_ELEM_PE_CONTEXT).

So far, I have no idea what would be a beautiful solution to hand-over this address.
Do you have any ideas?
Would OCSD_GEN_TRC_ELEM_ADDR_NACC be the correct type?

**Comment by mikel-armbb** [comment]
As a follow up...

The ETMv4 specification does not require a target address to be issued after an exception packet to mark the destination of the exception.

This would ordinarily occur only if the trace continues through the exception address. For exceptions taken into filtered or prohibited regions we cannot rely on an address packet appearing. 

This particular implementation is emitting an extra packet not needed to trace the areas of trace bounded by the filtering.

Closing issue as there is no practical solution which matches the ETMv4 protocol specification.

**Comment by albertschulz** [comment]
Thank you very much for your information.
As we can not rely on the packet being emitted, for sure there is no need to handle this.
