### ISSUE TITLE
ARM ETMv3.3 ISYNC decoding

### ISSUE THREAD

**Issue by Ammonoidea** [Linaro/OpenCSD#9]
Hello, I have been using OpenCSD to decode some ARM ETMv3.3 data, and I think there is an error when reading ISYNC packets. The address does not seem to be read correctly. It appears that when reading the ContextID, the index is updated twice. This causes junk to bread into the address.

**Comment by mikel-armbb** [comment]
Hi,
Can you provide some captured data that reproduces this fault, in the format use in the tests/snapshots directories so this may be investigated further 

Thanks

Mike

**Comment by mikel-armbb** [comment]
v0.7.1 removes the additional data index increment.
